#
# Python helpers for nextcloud-myanon.conf.
#
# Nextcloud uses the login name (uid) as a key in many tables, and also inside
# composite strings ('home::alice', '/alice/files/...', 'principals/users/alice',
# 'user:alice:<id>', JSON arguments). Every occurrence is replaced by the same
# fake uid, derived from an HMAC of the real one, so the instance stays
# consistent. File and folder names in users' files are renamed the same way,
# keeping their extension, and the MD5 path hashes are recomputed.
#
# Values arrive from myanon still SQL-escaped (without the surrounding
# quotes), so they are unescaped before processing and escaped again on the
# way out. Values that are not changed are returned exactly as received.
#

import hashlib
import hmac
import json
import mimetypes
import os
import re

import myanon_utils

# Accounts kept with their real login name (not personal, handy in dev)
KEEP_UIDS = {'admin'}

FAKE_DOMAIN = 'example.com'
FAKE_STREET = 'Example Street'
FAKE_CITY = 'Springfield'
FAKE_WEBSITE = 'https://example.com'
LOREM = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'

# Hash of 'password', generated by Nextcloud 35 (argon2id, no instance secret)
PASSWORD_HASH = '3|$argon2id$v=19$m=65536,t=4,p=1$WjNKZWFmekpTZVVsVkJiZA$sgUYdBsVLUmyxhKGBOG+M25xgRezSe1c2NxQoAnhus8'

# Top-level folders of a home storage that hold user-named files ('files' and
# 'trash' are also the roots of a group folder with its own storage)
_USER_ROOTS = {'files', 'files_versions', 'uploads', 'trash'}
_TRASH_ROOT = 'files_trashbin'           # files_trashbin/<files|versions|keys>/...
_SUFFIX_RE = re.compile(r'^(.*?)((?:\.v\d+)?(?:\.d\d+)?)$')   # versions, trash

_EXTRA_EXT = {'.md', '.odt', '.ods', '.odp', '.docx', '.xlsx', '.pptx', '.mkv', '.heic', '.webp', '.7z', '.log', '.yml', '.yaml', '.json', '.csv', '.sql', '.gz', '.bz2', '.xz'}

# \w matches Unicode letters too: josé@exemple.fr, 用户@例子.中国... but not
# combining accents, as in a decomposed 'jose\u0301@exemple.fr': add them.
_MARKS = '\u0300-\u036f\u1ab0-\u1aff\u1dc0-\u1dff\u20d0-\u20ff\ufe20-\ufe2f'
_EMAIL_RE = re.compile(r'[\w%s.%%+-]+@[\w%s-]+(?:\.[\w%s-]+)+' % ((_MARKS,) * 3))

# Profile properties (oc_accounts.data and oc_accounts_data)
_PROFILE_NAME = {'displayname'}
_PROFILE_EMAIL = {'email'}
_PROFILE_PHONE = {'phone'}
_PROFILE_ADDRESS = {'address'}
_PROFILE_WEBSITE = {'website'}
_PROFILE_BLANK = {'twitter', 'bluesky', 'fediverse', 'organisation', 'role',
                  'headline', 'biography', 'birthdate', 'pronouns'}

# JSON keys holding a uid (oc_jobs arguments, oc_files_versions metadata...)
_JSON_UID_KEYS = {'uid', 'user', 'userId', 'user_id', 'owner', 'author'}

# Background jobs whose argument is a list starting with a uid: [uid, fileid]
_JOB_UID_LISTS = {'OC\\FilesMetadata\\Job\\UpdateSingleMetadata'}


# ---------------------------------------------------------------------------
# Building blocks
# ---------------------------------------------------------------------------

def _digest(value):
    secret = myanon_utils.get_secret().encode('utf-8', 'surrogateescape')
    return hmac.new(secret, value.encode('utf-8', 'surrogateescape'), hashlib.sha256).digest()


def _letters(value, length):
    d = _digest(value)
    return ''.join(chr(ord('a') + d[i % len(d)] % 26) for i in range(length))


def _unesc(value):
    return myanon_utils.unescape_sql_string(value)


def _esc(value):
    return myanon_utils.escape_sql_string(value)


def _row(column):
    """Unescaped value of another column of the current row ('' if NULL)."""
    value = myanon_utils.get_row().get('`%s`' % column, '')
    return '' if value == 'NULL' else _unesc(value)


def _fake_uid(real):
    if not real or real in KEEP_UIDS:
        return real
    return 'u' + _letters('uid:' + real.lower(), 8)


def _fake_email(real):
    real = real.strip()
    if not real:
        return real
    return '%s@%s' % (_letters(real.lower(), 10), FAKE_DOMAIN)


def _fake_name(real):
    real = real.strip()
    if not real:
        return real
    return _letters(real, 7).capitalize()


def _fake_digits(real):
    d = _digest(real)
    out, i = [], 0
    for ch in real:
        if ch.isdigit():
            out.append(str(d[i % len(d)] % 10))
            i += 1
        else:
            out.append(ch)
    return ''.join(out)


def _known_ext(ext):
    """Keep an extension only when it is a real file type ('.pdf', '.jpg'...).
    A dotted name such as 'Jane.Doe' has no extension worth keeping."""
    return ext.lower() in mimetypes.types_map or ext.lower() in _EXTRA_EXT


def _scrub_text(text):
    return _EMAIL_RE.sub(lambda m: _fake_email(m.group(0)), text)


def _fake_segment(seg):
    """Rename a file or folder name, keeping its extension and the version
    (.v<timestamp>) or trash (.d<timestamp>) suffixes Nextcloud adds."""
    if not seg:
        return seg
    m = _SUFFIX_RE.match(seg)
    base, suffix = m.group(1), m.group(2)
    stem, ext = os.path.splitext(base)
    if not stem or not _known_ext(ext):   # '.htaccess', 'Jane.Doe'...
        stem, ext = base, ''
    return _letters('file:' + stem, 8) + ext + suffix


def _fake_path(path):
    """Rename the user-chosen parts of a home storage path, and the uid in
    avatar paths (appdata_<instance>/avatar/<uid>/...)."""
    parts = path.split('/')
    if parts[0].startswith('appdata_') and len(parts) > 2 and parts[1] == 'avatar':
        return '/'.join(parts[:2] + [_fake_uid(parts[2])] + parts[3:])
    if parts[0] in _USER_ROOTS:
        keep = 1
    elif parts[0] == _TRASH_ROOT and len(parts) > 1:
        keep = 2
    elif parts[0] == '__groupfolders' and len(parts) > 2:
        # Group folders created by older versions of the app: __groupfolders/<id>/... and
        # __groupfolders/trash/<id>/... (versions are named by file id and time)
        if parts[1].isdigit():
            keep = 2
        elif parts[1] == 'trash' and parts[2].isdigit():
            keep = 3
        else:
            return path
    else:
        return path
    return '/'.join(parts[:keep] + [_fake_segment(p) for p in parts[keep:]])


def _fake_profile(prop, real):
    if not real:
        return real
    if prop in _PROFILE_NAME:
        return _fake_name(real)
    if prop in _PROFILE_EMAIL:
        return _fake_email(real)
    if prop in _PROFILE_PHONE:
        return _fake_digits(real)
    if prop in _PROFILE_ADDRESS:
        return '%d %s, %s' % (_digest(real)[0] % 199 + 1, FAKE_STREET, FAKE_CITY)
    if prop in _PROFILE_WEBSITE:
        return FAKE_WEBSITE
    if prop in _PROFILE_BLANK:
        return ''
    return real


def _scrub_json(obj):
    """Map uid keys and replace e-mails in a decoded JSON structure."""
    if isinstance(obj, dict):
        return {k: (_fake_uid(v) if k in _JSON_UID_KEYS and isinstance(v, str) else _scrub_json(v))
                for k, v in obj.items()}
    if isinstance(obj, list):
        return [_scrub_json(v) for v in obj]
    if isinstance(obj, str):
        return _scrub_text(obj)
    return obj


def _json_dumps(obj):
    # Same compact form as PHP json_encode
    return json.dumps(obj, separators=(',', ':'))


# ---------------------------------------------------------------------------
# Functions called from nextcloud-myanon.conf
# ---------------------------------------------------------------------------

def uid(value):
    return _esc(_fake_uid(_unesc(value)))


def email(value):
    return _esc(_fake_email(_unesc(value)))


def name(value):
    return _esc(_fake_name(_unesc(value)))


def lorem(value):
    return LOREM if _unesc(value).strip() else value


def storage_id(value):
    """oc_storages.id: 'home::<uid>' or 'object::user:<uid>'."""
    real = _unesc(value)
    for prefix in ('home::', 'object::user:'):
        if real.startswith(prefix):
            return _esc(prefix + _fake_uid(real[len(prefix):]))
    return value


def principal(value):
    """'principals/users/<uid>' (DAV address books, calendars, shares)."""
    real = _unesc(value)
    prefix = 'principals/users/'
    if real.startswith(prefix):
        return _esc(prefix + _fake_uid(real[len(prefix):]))
    return value


def mount_point(value):
    """oc_mounts.mount_point: '/<uid>/' or '/<uid>/files/<path>/'."""
    real = _unesc(value)
    parts = real.strip('/').split('/', 1)
    if not parts[0]:
        return value
    new = '/' + _fake_uid(parts[0]) + '/'
    if len(parts) > 1 and parts[1]:
        new += _fake_path(parts[1]) + '/'
    return _esc(new)


def filecache_path(value):
    return _esc(_fake_path(_unesc(value)))


def filecache_name(value):
    """Last segment of the path, renamed exactly like filecache_path does."""
    path = _row('path')
    new_path = _fake_path(path)
    if new_path == path:
        return value
    return _esc(new_path.rsplit('/', 1)[-1])


def filecache_path_hash(value):
    return hashlib.md5(_fake_path(_row('path')).encode('utf-8', 'surrogateescape')).hexdigest()


def file_name(value):
    return _esc(_fake_segment(_unesc(value)))


def share_target(value):
    """oc_share.file_target: path inside the recipient's files, e.g. '/report.txt'."""
    real = _unesc(value)
    return _esc('/'.join(_fake_segment(p) for p in real.split('/')))


def share_with(value):
    share_type = _row('share_type')
    if share_type == '0':             # user
        return uid(value)
    if share_type == '4':             # e-mail
        return email(value)
    if share_type == '6':             # federated: user@server
        return _esc(_scrub_text(_unesc(value)))
    return value                      # group, link, circle...


def share_password(value):
    return PASSWORD_HASH if _unesc(value) else value


def circle_name(value):
    """oc_circles_circle.name: 'user:<uid>:<single id>' for personal circles."""
    real = _unesc(value)
    if real.startswith('user:'):
        parts = real.split(':')
        if len(parts) == 3:
            return _esc('user:%s:%s' % (_fake_uid(parts[1]), parts[2]))
    return value


def circle_display_name(value):
    return name(value) if _row('source') == '1' else value


def circle_member_uid(value):
    return uid(value) if _row('user_type') == '1' else value


def circle_member_name(value):
    return name(value) if _row('user_type') == '1' else value


def account_data(value):
    """oc_accounts.data: JSON object of profile properties."""
    try:
        data = json.loads(_unesc(value))
    except ValueError:
        return value
    for prop, entry in data.items():
        if isinstance(entry, dict) and isinstance(entry.get('value'), str):
            entry['value'] = _fake_profile(prop, entry['value'])
    return _esc(_json_dumps(data))


def account_value(value):
    """oc_accounts_data.value, one profile property per row."""
    return _esc(_fake_profile(_row('name'), _unesc(value)))


def preference(value):
    """oc_preferences.configvalue"""
    if (_row('appid'), _row('configkey')) == ('settings', 'email'):
        return email(value)
    real = _unesc(value)
    new = _scrub_text(real)
    return value if new == real else _esc(new)


def appconfig(value):
    """oc_appconfig.configvalue: a few keys hold a uid."""
    if (_row('appid'), _row('configkey')) == ('photos', 'lastPlaceMappedUser'):
        return uid(value)
    return value


def json_args(value):
    """JSON with uid keys and e-mails (oc_jobs.argument, oc_files_versions.metadata)."""
    real = _unesc(value)
    try:
        data = json.loads(real)
    except ValueError:
        new = _scrub_text(real)
        return value if new == real else _esc(new)
    new_data = _scrub_json(data)
    return value if new_data == data else _esc(_json_dumps(new_data))


def acl_mapping(value):
    """Group folders ACL and managers: a user, group or team id."""
    return uid(value) if _row('mapping_type') == 'user' else value


def job_argument(value):
    """oc_jobs.argument: JSON, sometimes a positional list starting with a uid."""
    if _row('class') in _JOB_UID_LISTS:
        try:
            data = json.loads(_unesc(value))
        except ValueError:
            return value
        if isinstance(data, list) and data and isinstance(data[0], str):
            data[0] = _fake_uid(data[0])
            return _esc(_json_dumps(data))
        return value
    return json_args(value)


def comment_actor(value):
    return uid(value) if _row('actor_type') == 'users' else value
