name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: autogen
      run: ./autogen.sh
    
    - name: configure
      run: ./configure
      
    - name: Install dependencies
      run: make
      
    - name: Run tests
      run: make check
